### ISSUE TITLE
Request pencarian data/json dengan nama desa di link demo site

### ISSUE THREAD

**Issue by hyuzea** [cahyadsn/wilayah#1]

**Comment by cahyadsn** [comment]
bisa dijelaskan format/contoh inputan dan output yang diharapkan ?

**Comment by hyuzea** [comment]
Ini ya Pak, jika boleh data jsonnya yang di link demo, saya mau jadikan sebagai service untuk aplikasi saya.

Ini misalnya pencarian dengan nama desa
GET /search-desa?query=$nama_desa 

result:
```javascript
{
	data: [
		{id:1, nama:"nama_desa"},
		{id:5, nama:"nama_desa"},
		// etc
	 ]
}
```
lalu dari hasil tesebut bisa di pilih satu (dropdownlist) untuk GET /detail-desa seperti yang sudah ada. Jadi ini pencariannya dengan nama desa bukan pencarian dari provinsi>kab>desa
seperti itu gambarannya
Thanks

**Comment by cahyadsn** [comment]
sebenernya sih mudah aja, tinggal query pake  SELECT * FROM wilayah WHERE namaLIKE '%nama_desa%' dapat list sesuai query yg diberikan, format hasil querynya utk dibuat dropdownlist, dan jika option di dropdownlistnya dipilih tinggal query lagi sesuai kode wilayahnya ke tabel wilayah .. simple like that :)

**Comment by dodysat** [comment]
Update data terakhir kapan itu bang?

**Comment by cahyadsn** [comment]
untak data di demo version, update data sesuai permendagri no 137 tahun 2017
http://cahyadsn.phpindonesia.id/wilayah

**Comment by cahyadsn** [comment]
-- closed

**Comment by cahyadsn** [comment]
-- pencarian secara langsung belum tersedia di versi open source
