### ISSUE TITLE
Invalid Data Integrity: Missing parent data (wilayah_2020.sql)

### ISSUE THREAD

**Issue by ammarfaizi2** [cahyadsn/wilayah#11]
# Related File
https://raw.githubusercontent.com/cahyadsn/wilayah/44aad13e92f8b469cf5ee119870a09dd4e1cdc7e/wilayah_2020.sql

# Invalid Data Integrity
kode | nama
-- | --
19.09.11.2001 | Pagar Gunung
19.09.11.2002 | Karang Nanding
19.09.11.2003 | Semidang
19.09.11.2004 | Gajah Mati
19.09.11.2005 | Padang Siring
19.09.11.2006 | Lagan Bungin
19.09.11.2007 | Pagar Jati
19.09.11.2008 | Taba Lagan
19.09.11.2009 | Lagan
19.09.11.2010 | Bukit
19.09.11.2011 | Kota Niur

# Emphasize The Problem
kode | nama
-- | --
19 | KEPULAUAN BANGKA BELITUNG
19.09 | ???? (where is this?)
19.09.11 | ???? (where is this?)

# Future Solution
Please normalize the table and use foreign key constraint to prevent this mistake in the future. Thank you.

**Comment by cahyadsn** [comment]
thanks you, there are some 'typo' on area code, the right code 'll be:

17.09.11.2001 | Pagar Gunung
17.09.11.2002 | Karang Nanding
17.09.11.2003 | Semidang
17.09.11.2004 | Gajah Mati
17.09.11.2005 | Padang Siring
17.09.11.2006 | Lagan Bungin
17.09.11.2007 | Pagar Jati
17.09.11.2008 | Taba Lagan
17.09.11.2009 | Lagan
17.09.11.2010 | Bukit
17.09.11.2011 | Kota Niur
