### ISSUE TITLE
Arti data lat/lon

### ISSUE THREAD

**Issue by sicenul** [cahyadsn/wilayah#13]
Mohon informasi, apakah arti dari data lat/lon pada demo aplikasi?
* Apakah merupakan titik tengah dari batas wilayah provinsi atau kab/kota?, atau
* Apakah merupakan titik dari ibukota wilayah provinsi atau kab/kota?

Mohon petunjuk.
Terima kasih.

**Comment by irlfdyh** [comment]
setahu saya, lat/lon itu singkatan dari latitude/longitude yang biasa dipakai untuk menentukan posisi geografis dari suatu tempat

**Comment by cahyadsn** [comment]
- untuk wilayah yg SUDAH diketahui/didapat lat/long (koordinat) dari ibukota-nya (provinsi/kab/kota/desa/kelurahan) maka nilai lat/long-nya diambil dari nilai lat/long ibukotanya tersebut
- untuk wilayah yg BELUM diketahui/didapat lat/long (koordinat) dari ibukota-nya maka dibuat nilai lat/long-nya merupakan titik tengah berdasarkan nilai points boundaries/polygon (field 'path') dari wilayah tersebut
- untuk daerah/wilayah yang BELUM diketahui/didapat titik-titik boundariesnya, ditentukan 4 titik boundareis (kiri-atas/barat laut; kanan-atas/timur laut; kanan-bawah/tenggara dan kiri-bawah/barat daya) dari wilayah tersebut 

**notes:**
- beberapa koordinat ibukota (lat/long) dicari secara manual, demikian pun dengan boundaries-nya karena keterbatasan sumber data, sehingga masih cukup banyak yang belum sesuai dgn yg diharapkan

**Comment by sicenul** [comment]
@irlfdyh , terima kasih sudah ikut merespon
@cahyadsn , terima kasih atas informasinya, sangat clear.
