### ISSUE TITLE
Ada nama kabupaten yang sudah berubah nama

### ISSUE THREAD

**Issue by bungkusansayuran** [cahyadsn/wilayah#14]
Menurut Permendagri 72 tahun 2019 https://www.kemendagri.go.id/files/2020/PMDN%2072%20TH%202019+lampiran.pdf
halaman 3321
76.01 KAB. PASANGKAYU bukan KAB. MAMUJU UTARA
halaman 3372
81.03 KAB. KAB. KEPULAUAN TANIMBAR  bukan KAB. MALUKU TENGGARA BARAT

**Comment by cahyadsn** [comment]
Terima kasih atas koreksinya, data sudah diubah dan diperbaharui
