### ISSUE TITLE
Tidak ditemukan kode parent kecamatan berikut ...

### ISSUE THREAD

**Issue by sugenk** [cahyadsn/wilayah#2]
FYI, saya coba import dump dari sql terbaru yang ini
https://github.com/cahyadsn/wilayah/blob/master/wilayah_2018.sql

tidak ditemukan kecamatan dengan kode berikut :
13.02.02
16.01.20
16.01.28
16.02.02
16.02.17

sehingga desa/kelurahan berikut ini tidak punya kecamatan ?
13.02.02.1036	Ikua Koto Dibalai
16.01.20.2001	Kelumpang
16.01.20.2002	Gunung Tiga
16.01.20.2003	Mendingin
16.01.20.2004	Ulak Lebar
16.01.20.2005	Pedataran
16.01.20.2006	Sukajadi
16.01.20.2007	Belandang
16.01.28.2001	Bandar Jaya
16.01.28.2002	Karang Endah
16.01.28.2003	Pajar Bulan
16.01.28.2004	Pagar Dewa
16.01.28.2005	Bumi Kawa
16.01.28.2006	Tanjunglengkayap
16.01.28.2007	Lubuk Dalam
16.01.28.2008	Negeri Ratu
16.01.28.2009	Segara Kembang
16.01.28.2010	Tihang
16.01.28.2011	Lubuk Hara
16.01.28.2012	Sukaraja
16.01.28.2013	Negeri Agung
16.01.28.2014	Gedung Pekuon
16.01.28.2015	Tualang
16.01.28.2016	Sundan
16.01.28.2017	Bunga Tanjung
16.01.28.2018	Way Heling
16.01.28.2019	Umpam
16.01.28.2020	Fajar Jaya
16.01.28.2021	Simpang Empat
16.01.28.2022	Tanjungagung
16.02.02.2001	Ulak Kapal
16.02.02.2002	Tanjung Merindu
16.02.02.2003	Tanjung Baru
16.02.02.2004	Seritanjung
16.02.02.2005	Pengaraian
16.02.02.2006	Sukarami
16.02.02.2008	Sukamulya
16.02.02.2010	Pulau Gemantung
16.02.02.1011	Tanjung Lubuk
16.02.02.2012	Bumiagung
16.02.02.2013	Kotabumi
16.02.02.2014	Tanjung Beringin
16.02.02.2015	Tanjung Laga
16.02.02.2016	Tanjung Laut
16.02.02.2017	Ulak Balam
16.02.02.2018	Jambu Ilir
16.02.02.2031	Jukdadak
16.02.02.2032	Atar Balam
16.02.02.2033	Tanjung Harapan
16.02.02.2034	Pulau Gemantung Ilir
16.02.02.2035	Pulau Gemantung Ulu
16.02.02.2036	Pulau Gemantung Darat
16.02.17.2001	Tanjung Aur
16.02.17.2002	Lubuk Ketepeng
16.02.17.2003	Talang Cempedak
16.02.17.2004	Bubusan
16.02.17.2005	Air Itam
16.02.17.2006	Jejawi
16.02.17.2007	Karang Agung
16.02.17.2008	Muara Batun
16.02.17.2009	Lingkis
16.02.17.2010	Terusan Jawa
16.02.17.2011	Tanjung Ali
16.02.17.2012	Sukadarma
16.02.17.2013	Ulak Tembaga
16.02.17.2014	Pedu
16.02.17.2015	Pematang Kijang
16.02.17.2016	Simpang Empat
16.02.17.2017	Padang Bulan
16.02.17.2018	Batun Baru
16.02.17.2019	Danau Ceper

**Comment by sugenk** [comment]
13.02.02.1036	Ikua Koto Dibalai, ada kemungkinan redundant dengan 
13.76.02.1036	Ikua Koto Dibalai, yang mempunya parent ...
  13.76.02	Payakumbuh Utara	(kecamatan)
  13.76	KOTA PAYAKUMBUH	(kota)
  13	SUMATERA BARAT	(provinsi)

sedangkan untuk kode kecamatan lainnya, kemungkinan adalah
16.01.20	Ulu Ogan
16.01.28	Lengkiti
16.02.02	Tanjung Lubuk
16.02.17	Jejawi

:100:

**Comment by cahyadsn** [comment]
ok. terima kasih informasinya, data wilayah_2018.sql fixed
