### ISSUE TITLE
Ada Data Desa Yang Salah

### ISSUE THREAD

**Issue by switchid** [cahyadsn/wilayah#20]
Menurut Kepmendagri berserta Lampiran Nomor 146.1-4717 Tahun 2020 Tentang Penetapan Nama, Kode dan Jumlah Desa Seluruh Indonesia Tahun 2020, ada data desa yang salah tempat desa kenanten yang seharusnya masuk kecamatan puri dan desa gayaman yang seharusnya masuk kecamatan mojoanyar masuk ke puri. bisa di lihat di halaman 1224.

**Comment by cahyadsn** [comment]
Terima kasih atas koreksinya.
- 35.16.18.2013, Gayaman, Semula Kec Puri Srt Bup 411.2/878/414-112/2019, 35.16.11.2015, Gayaman
- 35.16.11.2017, Kenanten, Semula Kec Mojoanyar Srt Bup 411.2/878/414-112/2019, 35.16.18.2007, Kenanten
