### ISSUE TITLE
Field nama kurang besar?

### ISSUE THREAD

**Issue by sugiana** [cahyadsn/wilayah#24]
Saya menemukan kode 12.09.23.2003 dengan nama berakhiran garis miring yaitu `Perkebunan Sei Dadap III/`. Saat cek di https://www.kemendagri.go.id/files/2020/PMDN%2072%20TH%202019+lampiran.pdf halaman 428 nama yang benar adalah `Perkebunan Sei Dadap III/IV`. Sarannya adalah menambah ukuran field nama dari 25 menjadi 64.

**Comment by cahyadsn** [comment]
Terima kasih atas koreksinya, untuk file wilayah.sql sudah disesuaikan panjang field nama-nya menjadi 100, namun disarankan untuk menggunakan file db yang terbaru (wilayah_2020.sql) karena file wilayah.sql masih menggunakan data berdasarkan  Permendagri No 56 Tahun 2015. file wilayah_2020.sql menggunakan data berdasarkan Permendagri No. 72 Tahun 2019 (revised by Kepmendagri No.146.1-4717 Tahun 2020), sedangkan utk update terbaru yag berdasarkan Permendagri No 58 Tahun 2021 (wilayah_2022.sql) masih dalam proses penyusunan karena lampiran data resmi dari depdagri belum saya dapatkan
