### ISSUE TITLE
PDF sumber asli

### ISSUE THREAD

**Issue by hprtama** [cahyadsn/wilayah#25]
Dear Pak @cahyadsn , bila berkenan untuk menyertakan juga PDF dari sumber aslinya, agar memudahkan crosscheck. Saat ini sumber informasi publik yang tersedia terbaru yaitu Permendagri no 72 tahun 2019, walaupun di beberapa pemberitaan memang ada update terhadap peraturan tersebut. Terima kasih

**Comment by cahyadsn** [comment]
Untuk file PDF karena cukup besar maka tidak saya sertakan dalam repo ini, untuk beberapa tautan dan file sourcenya bisa ditemui di repo berikut : https://github.com/cahyadsn/wilayah_ref
