### ISSUE TITLE
Provinsi di Pulau Papua perlu di perbarui

### ISSUE THREAD

**Issue by dendyadinirwana** [cahyadsn/wilayah#27]
Perlu ada revisi menyesuaikan undang-undang (UU) tentang pembentukan tiga provinsi baru di Papua. Tiga provinsi baru di Papua itu adalah Papua Selatan, Papua Tengah, dan Papua Pegunungan.

**Comment by cahyadsn** [comment]
1. Kode data wilayah dan pulau di buat oleh Kemendagri, dan hingga saat ini BELUM ada Permendagri/Kepmendagri terkait kode wilayah/kode pulau yang merupakan penjabaran dari UU No 14 sd 16 th 2022 mengenai Pembentukan Provinsi Papua Selatan, Papua Tengah dan Papua Pegunungan tersebut
2. Ini bukan issue aplikasi karena diluar kewenangan developer mengenai update data kode wilayah, karena hal tersebut menjadi kewenangan Kemendagri
