### ISSUE TITLE
Konversi kode wilayah lama ke yang baru (pemekaran) 

### ISSUE THREAD

**Issue by nandaza** [cahyadsn/wilayah#28]
mas, punya table mapping untuk wilayah yg mengalami pemekaran dari permendagri 2019 ke kepmendagri 2022?

contoh:
kelurahan airputih kecamatan tampan kota pekanbaru provinsi riau (14.71.08.1011)
pemekaran menjadi
kelurahan airputih kecamatan tuahmadani kota pekanbaru provinsi riau (14.71.13.1005)

**Comment by cahyadsn** [comment]
Untuk table mapping secara khusus belum ada, tapi informasi seperti itu bisa dilihat dilihat di bagian lampiran dari Kepmendagri No. 050-145 Tahun 2022 tersebut.

bisa dilihat di repo https://github.com/cahyadsn/wilayah_ref
