### ISSUE TITLE
Kesalahan data path di table wilayah_1_2 untuk Kota Banjar

### ISSUE THREAD

**Issue by ibobgunardi** [cahyadsn/wilayah#29]
mantap sekali kak, saya izin pakai ya. Saya menemukan adanya kesalahan path untuk Kota Banjar di Provinsi Jawa Barat.
pathnya sama dengan Kab. Bandung Barat.

terimakasih kak.

**Comment by cahyadsn** [comment]
data path kota banjar telah di update, terima kasih atas koreksinya
