### ISSUE TITLE
Adakah filter untuk jenis kabupaten:kota dan kelurahan:desa

### ISSUE THREAD

**Issue by khayatzen** [cahyadsn/wilayah#3]
Saya lihat nggak ada filter untuk jenis kabupaten:kota dan kelurahan:desa. Karena pentingnya filter data tersebut mengenai status hukum wilayah tersebut. Desa status hukumnya berbeda dengan Kelurahan. Begitu pun Kabupaten dan Kotamadya.

Bisakah dibantu pengayaan data untuk status kelurahan:desa atau kabupaten:kota berdasar dbdata yang sudah njenengan punya?

**Comment by anovsiradj** [comment]
kalo secara kolom di tablenya, saya lihat tidak disediakan.

tapi untuk kab/kota bisa disaring pakai cara
`... lower(nama) like 'kab.%' ...` atau `... lower(nama) like 'kota %' ...`

**Comment by cahyadsn** [comment]
bisa dilihat dari kode wilayahnya:
KAB/KOTA
- sebagai patokan adalah digit angka ke tiga
-digit angka ke tiga = 0 atau 1 berarti kabupaten
-digit angka ke tiga =2 berarti kota

contoh:
32.04 -> digit angka ke-3 adalah nol(0) maka kabupaten, yaitu kabupaten Bandung
32.73 -> digit angka ke-3 adalah tujuh(7) maka kota, dalam hal ini kota Bandung

DESA/KELURAHAN
sebagai patokan adalah digit angka ke 7
- digit angka ke tujuh =1 berarti kelurahan
- digit angka ke tujuh =2 berarti desa

32.04.32.1001 -> digit angka ke-7 adalah 1, maka kelurahan, dlm hal ini adalah kelurahan Baleendah
32.04.32.2006 -> digit angka ke-7 adalah 2, maka desa, dlm hal ini adalah  desa Rancamanyar

**Comment by cahyadsn** [comment]
Ilustrasi dalam SQL dengan dialek MySQL/Maria DB:

-- membedakan kota atau kabupaten
SELECT
IF(SUBSTRING(kode,3,1)=7,'kota','kabupaten')) AS kota_kab
FROM
wilayah
WHERE
CHAR_LENGTH(kode)=5

-- membedakan kelurahan atau desa
SELECT
IF(SUBSTRING(kode,10,1)=1,'kelurahan','desa')) AS kel_desa
FROM
wilayah
WHERE
CHAR_LENGTH(kode)=13

**Comment by khayatzen** [comment]
Suwum om @cahyadsn dan @anovsiradj 
It works
