### ISSUE TITLE
GUNUNGKIDUL Kurang Spasi

### ISSUE THREAD

**Issue by sugiana** [cahyadsn/wilayah#31]
Kabupaten `GUNUNGKIDUL` seharusnya tertulis `GUNUNG KIDUL` di file `wilayah_2022.sql`

**Comment by cahyadsn** [comment]
sesuai dengan LAMPIRAN KEPUTUSAN MENTERI DALAM NEGERI NOMOR 050-145 TAHUN 2022 TENTANG PEMBERIAN DAN PEMUTAKHIRAN KODE, DATA WILAYAH ADMINISTRASI PEMERINTAHAN DAN PULAU TAHUN 2021 Bagian B. n. 3) KAB. GUNUNGKIDUL PROVINSI DAERAH ISTIMEWA YOGYAKARTA, Hal 1688 tertulis KAB. GUNUNGKIDUL (tanpa spasi)

bisa di baca di : https://github.com/cahyadsn/wilayah_ref/blob/main/docs/lamp/kepmendagri.050-145.th2022/lamp.kepmendagri.050-145.th.2022.lamp.b.34.pdf
