### ISSUE TITLE
Kecamatan mandiangin timur kodenya geser 1 dengan yang di file pdf Kepmen 050-145

### ISSUE THREAD

**Issue by bruriwijayanto** [cahyadsn/wilayah#33]
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/10410434/212229221-c66ab0f5-cf47-4c8e-903f-36dbbb5d1ed3.png">

**Comment by cahyadsn** [comment]
data sudah diperbaiki, terima kasih atas koreksinya
