### ISSUE TITLE
kesalahan nama kecamatan 62.10.01

### ISSUE THREAD

**Issue by bruriwijayanto** [cahyadsn/wilayah#34]
kesalahan nama kecamatan 62.10.01 kecamatan Sepang ditulis Sepang Simin, Sepang Simin adalah salah satu kelurahan di Sepang bukan nama kecamatannya
<img width="1430" alt="Screenshot 2023-01-27 at 5 50 59 PM" src="https://user-images.githubusercontent.com/10410434/215070641-4d815c72-9a35-41b7-93f2-2b274d2ff0db.png">

**Comment by cahyadsn** [comment]
Data sudah diupdate, terima kasih atas koreksi-nya
