### ISSUE TITLE
penambahan kecamatan dan desa baru di kabupaten natuna

### ISSUE THREAD

**Issue by bruriwijayanto** [cahyadsn/wilayah#35]
penambahan kecamatan dan desa baru di kabupaten natuna 21.03.23 dan 21.03.24
![natuna WhatsApp Image 2023-02-06 at 9 52 37 AM](https://user-images.githubusercontent.com/10410434/216877000-4f1bed37-eba8-4744-b442-523541968697.jpeg)

**Comment by cahyadsn** [comment]
mohon untuk di sertakan juga dasar hukumnya (kep/per mendagri no/th, dan no halaman-nya)

**Comment by cahyadsn** [comment]
data sudah diupdate sesuai Kepmendagri No 100.1.1-6117
