### ISSUE TITLE
penambahan kecamatan tongauna utara

### ISSUE THREAD

**Issue by bruriwijayanto** [cahyadsn/wilayah#36]
|kodelokasi   |lokasi        |
|-------------|--------------|
|74.02.42     |Tongauna Utara|                
|74.02.42.2001|Waworonda Jaya|                
|74.02.42.2002|Uluao         |                
|74.02.42.2003|Sanuanggamo   |                
|74.02.42.2004|Anggohu       |                
|74.02.42.2005|Ambopi        |                
|74.02.42.2006|Nambeaboru    |                
|74.02.42.2007|Puundombi     |                
|74.02.42.2008|Olo Onua      |                
|74.02.42.2009|Barowila      |                
|74.02.42.2010|Andalambe     |

**Comment by cahyadsn** [comment]
mohon untuk di sertakan juga dasar hukumnya (kep/per mendagri no/th, dan no halaman-nya)

**Comment by cahyadsn** [comment]
Data sudah diupdate sesuai  Kepmendagri No 100.1.1-6117 Tahun 2022
