### ISSUE TITLE
desa pindah kecamatan dari tongauna ke tongauna utaraq

### ISSUE THREAD

**Issue by bruriwijayanto** [cahyadsn/wilayah#37]
<img width="523" alt="image" src="https://user-images.githubusercontent.com/10410434/216928438-765963d1-3607-47ce-9354-01af5358b62a.png">

**Comment by cahyadsn** [comment]
mohon untuk di sertakan juga dasar hukumnya (kep/per mendagri no/th, dan no halaman-nya)

**Comment by cahyadsn** [comment]
Data sudah diupdate sesuai Kepmendagri No 100.1.1.6117 Tahun 2022
