### ISSUE TITLE
Pemekaran provinsi PAPUA

### ISSUE THREAD

**Issue by sicenul** [cahyadsn/wilayah#39]
Berikut ini Kepmendagri yang didalamnya terdapat pemekaran provinsi di PAPUA:
KEPMENDAGRI NOMOR 100.1.1-6117 TAHUN 2022
Karena ukuran file sekitar 56MB maka bisa diunduh disini: https://filetransfer.io/data-package/pB9utMxj

**Comment by cahyadsn** [comment]
terima kasih atas informasi dan dokumennya, update data on progress
