### ISSUE TITLE
Data Wilayah dengan Koma, ada yang salah

### ISSUE THREAD

**Issue by khairaniummah** [cahyadsn/wilayah#4]
Ada beberapa desa yang terdapat koma, dan saya cek dengan data kemendagri ada beberapa yang belum benar, yaitu:
1671021006	7 Ulu,Ulu,9-10 Ulu >>>>> Seharusnya "7 Ulu" saja
6102011009	Terusan,Pasir Palembang >>>>> Seharusnya "Terusan" saja
6102071011	Sungai Pinyuh,Pak Bulu >>>>> Seharusnya "Sungai Pinyuh" saja

Dan ada 3 Desa yang ada kelebihan koma:
1674011001   Prabumulih
6472101005  Rapak Dalam
7401041007   Tahoa

Anyway, **terima kasih banyaaak** untuk membagikan data wilayah ini dan keep it updated, really helpful for my project :) Jika butuh file SQL untuk SQL Server, I already made it from this data hoho

**Comment by cahyadsn** [comment]
Data wilayah_2018.sql  sudah diperbaiki dengan memperbaiki dan/atau menghilangkan tanda koma (,) di beberapa record
