### ISSUE TITLE
Duplikasi kode : wilayah.sql

### ISSUE THREAD

**Issue by flamrdevs** [cahyadsn/wilayah#40]
Saya telah membuat script untuk melakukan pengecekan kode wilayah yang sama, dan terdapat hasil sebagai berikut.

Result

![image](https://github.com/cahyadsn/wilayah/assets/71713464/0eb038b1-d299-4814-a9d1-d27cb2d1d53f)

SQL Query

![image](https://github.com/cahyadsn/wilayah/assets/71713464/a9e09149-0f6e-4295-a7b3-d3708730a16e)

![image](https://github.com/cahyadsn/wilayah/assets/71713464/a568d6f1-03e9-4001-beff-e611997e6fc6)

**Comment by cahyadsn** [comment]
terima kasih koreksinya, data sudah diupdate
