### ISSUE TITLE
Konfirmasi Data Kecamatan

### ISSUE THREAD

**Issue by Jaluanda** [cahyadsn/wilayah#42]
Mohon informasi koreksinya yang benar untuk data kecamatan berikut:
![image](https://github.com/cahyadsn/wilayah/assets/11334082/8b9e0438-e845-4adf-b1ad-f22459d76a78)

Bila disandingkan dengan data di Wiki (mohon koreksi):
![image](https://github.com/cahyadsn/wilayah/assets/11334082/632c180f-42d2-46db-84ca-475b7ae794e0)

**Comment by cahyadsn** [comment]
Berdasarkan dokumen Kepmendagri No 100.1.1-6117 Tahun 2022, pada lampiran halaman 2268 dan 2311, nama Kecamatan untuk kode wilayah 52.71.05 adalah **Selaprang**.
![image](https://github.com/cahyadsn/wilayah/assets/3700401/dbb2ec26-6cda-4360-875d-5362e860051b)
![image](https://github.com/cahyadsn/wilayah/assets/3700401/1215a6e4-c060-438b-bd8d-d96cf7dc3326)

**Comment by Jaluanda** [comment]
Terimakasih atas pencerahannya.
