### ISSUE TITLE
Seputar kode pos

### ISSUE THREAD

**Issue by TriyogaGP** [cahyadsn/wilayah#43]
@cahyadsn maaf mas mau nanya nih, di db sql nya tidak ada field untuk kode pos nya yaa ?

**Comment by cahyadsn** [comment]
@TriyogaGP untuk public repo ini sebenarnya hanya fokus ke data kode wilayah, sehingga utk kodepos, koordinat (latitude, longitude) , boundaries (polygon) tidak termasuk . Kalaupun ada itu 'bonus' saja

**Comment by feryardiant** [comment]
Untuk kode pos mungkin bisa cek repo https://github.com/w3appdev/kodepos, yang kebetulan juga saya pakai di salah satu project saya https://github.com/creasico/laravel-nusa. Walaupun data kode pos yang tersedia di repo tersebut belum lengkap (https://github.com/creasico/laravel-nusa/issues/41) tapi setidaknya sudah cukup membantu.

**Comment by TriyogaGP** [comment]
@feryardiant terimakasih mas,, untuk kodepos saya build sendiri jadi nya ditambahkan di DB saya .. kalau svg map kira2 ada referensi gak mas ?
@cahyadsn terimakasih mas ..

**Comment by feryardiant** [comment]
> kalau svg map kira2 ada referensi gak mas

Untuk SVG map saya belum nemu, tapi saya sempet nemu yang provide geojson. Cuma saya lupa link repo nya. Nanti kalo ketemu lagi saya cantumkan disini.

Dulu iseng jg nyari repo yang dengan label wilayah indonesia kalo gak salah.

**Comment by TriyogaGP** [comment]
@feryardiant terimakasih mas..

**Comment by rez-f** [comment]
@TriyogaGP Kalau perlu SVG map bisa juga kok digenerate sendiri mas, dapat dilakukan dengan mendownload Shapefile  Wilayah Indonesia (contoh: [indonesia-geospasial](https://www.indonesia-geospasial.com/2020/05/download-data-peta.html)) kemudian menggunakan tools [Mapshaper](https://github.com/mbloch/mapshaper) kita dapat menggenerate berbagai macam map file sesuai kebutuhan (TopoJSON, GeoJSON, SVG dan sebagainya).

**Comment by cahyadsn** [comment]
FYI untuk data kodepos vs kode wilayah sesuai Kepmendagri No 100.1.1-6117 Tahun 2022 ada di repo dengan tautan https://github.com/cahyadsn/wilayah_kodepos

**Comment by TriyogaGP** [comment]
terimakasih mas ..

Pada Sel, 6 Agu 2024 pukul 09.35 Cahya DSN ***@***.***>
menulis:
