### ISSUE TITLE
Konfirmasi nama daerah yang memiliki keterangan "Perbaikan nama ..."

### ISSUE THREAD

**Issue by ikhsan-rfl** [cahyadsn/wilayah#44]
saya lihat di dokumen "Keputusan Menteri Dalam Negeri Nomor 100.1.1-6117 Tahun 2022" yang didapat dari https://github.com/cahyadsn/wilayah_ref, jika di dokumen terdapat keterangan "Perbaikan nama ..." saat di cek dengan data yg ada di wilayah.sql masih menggunakan data lama, berikut contoh nya:

![image](https://github.com/cahyadsn/wilayah/assets/40913108/ed9cd4b0-b948-465d-9761-470ddc6133fb)

tertulis di wilayah.sql "KAB. PAHUWATO" yg seharusnya "KAB. POHUWATO"

![image](https://github.com/cahyadsn/wilayah/assets/40913108/abdc3ef9-878b-40d5-8d8d-5ed35afd5d04)

mohon koreksinya apakah benar atau memang ada dokumen terbaru ?

**Comment by cahyadsn** [comment]
terima kasih atas koreksinya, data sudah diupdate

**Comment by ikhsan-rfl** [comment]
maaf kesalahan data bukan hanya ada di "KAB. PAHUWATO" akan tetapi hampir semua wilayah yang memiliki keterangan "Perbaikan nama dari ..... menjadi ....." & "Perbaikan nama ..... semula .... menjadi ....." dan sejenisnya.

contoh:
"Johan Pahwalan" yg seharusnya "Johan Pahlawan"
![image](https://github.com/cahyadsn/wilayah/assets/40913108/c6a3b1e9-16f3-4af6-8e16-7306f42442f5)
![image](https://github.com/cahyadsn/wilayah/assets/40913108/e78684e2-8a5a-4160-8ad4-5d8125e6014e)

"Lam Kuta" yg seharusnya "Lamkuta"
![image](https://github.com/cahyadsn/wilayah/assets/40913108/49f96e80-0dc6-4620-ac90-9b057952c0e6)
![image](https://github.com/cahyadsn/wilayah/assets/40913108/826645da-3776-461c-9fb7-ff297068c8dc)

"Dayah Tungku" yg seharusnya "Dayah Teungku"
![image](https://github.com/cahyadsn/wilayah/assets/40913108/4cdee9cd-b444-4037-a837-05bfda403b0e)
![image](https://github.com/cahyadsn/wilayah/assets/40913108/45693b2a-43c6-40c9-913b-db8e35f688da)
