### ISSUE TITLE
PostgreSQL compatibility 

### ISSUE THREAD

**Issue by mininxd** [cahyadsn/wilayah#52]
Tolong tambahkan db untuk postgre kalau itu sumbernya dari dump 
 
```sql
mysqldump --compatible=postgresql
```

**Comment by cahyadsn** [comment]
utk wilayah.sql dan pulau.sql bisa digunakan di mysql,mariadb maupun postgres, silakan sesuaikan untuk db/schema yang digunakan, atau jika ada yang kurang sesuai silakan buat sendiri dari souce data aslinya di tulis ulang ke format query postgres atau db yg diinginkan, proses-nya tidak sulit kok

**Comment by mininxd** [comment]
gk ada pc bang, makanya request hehe
