### ISSUE TITLE
File `db/archive/wilayah_level_1_2.sql` bermasalah di commit `957e4df`

### ISSUE THREAD

**Issue by feryardiant** [cahyadsn/wilayah#53]
Dear pak @cahyadsn 

Bisa tolong di cek kembali file [`db/archive/wilayah_level_1_2.sql`](https://github.com/cahyadsn/wilayah/blob/master/db/archive/wilayah_level_1_2.sql) sepertinya masih ada unresolved merge conflict di commit 957e4df

Terima kasih sebelumnya

**Comment by cahyadsn** [comment]
terima kasih informasinya, file tersebut sudah di re-solve
