### ISSUE TITLE
duplikat kode

### ISSUE THREAD

**Issue by nexjson** [cahyadsn/wilayah#7]
pada wilayah terdapat beberapa duplikat kode pada wilayah_2020
ml Descending 1
kode
13
12.03.32.2003
2
16.03.22.2001
2
16.03.21.2003
2
16.03.22.2006
2
16.03.22.2002
2
16.03.21.2004
2
16.03.22.2007
2
21.03.11.2003
2
16.03.21
2
16.03.22.2003
2
16.03.21.2005
2
16.03.22.2008
2
21.03.11.2004
2
16.03.21.2001
2
16.03.22.2004
2
16.03.21.2006
2
21.03.11
2
16.03.22
2
21.03.11.2005
2
16.03.21.2002
2
16.03.22.2005
2
16.03.21.2007
2
21.03.11.2001
1
81.06.06.2002
1
91.17.05.2008

**Comment by cahyadsn** [comment]
terima kasih atas koreksinya, data sudah diperbaiki
