### ISSUE TITLE
duplikat kodewilayah  di file 2020

### ISSUE THREAD

**Issue by deval** [cahyadsn/wilayah#8]
untuk 2020 masih ada kode wilayah yg double: 21.03.11

**Comment by cahyadsn** [comment]
Perbaikan kode wilayah untuk wilayah kecamatan :
'21.04.11','Katang Bidare'
'21.04.12','Temiang Pesisir'
dan
'21.04.13','Bakung Serumpun'
termakasih atas koreksinya
