### ISSUE TITLE
Duplicate Data

### ISSUE THREAD

**Issue by indralionardy** [cahyadsn/wilayah#9]
Halo,

Dari data sql wilayah_2020 yang sudah di update masih ada data duplicate yaitu:

kode                       Jumlah duplicate
16.03.21.2006	2
16.03.26.2007	2

Thank you

**Comment by cahyadsn** [comment]
Kode wilayah berikut sudah diperbaiki
16.03.21.2006 Teluk Jaya
16.03.21.2007 Tanjung Medang
16.03.26.2006 Kuripan
16.03.26.2007 Kuripan Selatan
